interface CategoryTypes {
  [key: string]: string[];
}

export const categoryTypes: CategoryTypes = {
  Tops: [
    "T-Shirts",
    "Long Sleeves",
    "Sleeveless",
    "Polo Shirts",
    "Tanks & Camis",
    "Crop Tops",
    "Blouse",
    "Sweatshirts",
    "Hoodies",
    "Sweaters",
    "Sweater Vests",
    "Sports Tops",
    "Body Suit",
  ],
  Dresses: [
    "Mini Dresses",
    "Formal Dresses",
    "Maxi Dresses",
    "Bodycon Dresses",
    "Wrap Dresses",
    "Shirt Dresses",
    "Sweater Dresses",
    "Sundresses",
    "Jumpsuits",
  ],
  Pants: [
    "Jeans",
    "Chinos",
    "Shorts",
    "Trousers",
    "Leggings",
    "Sweatpants",
    "Joggers",
    "Track Pants",
    "Cargo Pants",
    "Wide Leg Pants",
    "Culottes",
  ],
  Skirts: ["Mini Skirts", "Midi Skirts", "Maxi Skirts"],
  Outerwear: [
    "Jackets",
    "Coats",
    "Hoodies",
    "Sweaters",
    "Vests",
    "Blazers",
    "Puffer Jackets",
    "Windbreaker",
    "Cardigans",
    "Ponchos",
  ],
  Shoes: [
    "Sneakers",
    "Slip Ons",
    "Sports Shoes",
    "School Shoes",
    "Boots",
    "Sandals",
    "Sandal Heels",
    "Mule Heels",
    "Flat Shoes",
    "Slides",
    "Combat Boots",
    "Hiking Shoes",
  ],
  Bags: [
    "Backpacks",
    "Tote Bags",
    "Shoulder Bags",
    "Crossbody Bags",
    "Clutches",
    "Satchels",
    "Fanny Packs",
    "Drawstring",
    "Messenger Bags",
    "Duffel Bags",
    "Luggage Bags",
    "Briefcases",
  ],
  Jewelry: ["Necklaces", "Watch", "Bracelets", "Earrings", "Rings", "Brooces/Pins"],
  Headwear: ["Hats", "Caps", "Scarves", "Sun Hats", "Bunnet", "Beanie"],
  OtherItems: [
    "Socks",
    "Belts",
    "Gloves",
    "Undergarments",
    "Loungewear",
    "Swimwear",
  ],
};
