export const MATERIAL_lIST = [
    { name: "White", image: "#FFFFFF" },
    { name: "Cream", image: "#FFFDD0" },
    { name: "Beige", image: "#E2C79C" },
    { name: "Light-Gray", image: "#E4E2E2" },
    { name: "Dark-Gray", image: "#B0B0B0" },
    { name: "Black", image: "#000000" },
    { name: "Light-Pink", image: "#FFEEEE" },
    { name: "Yellow", image: "#FFFF00" },
    { name: "Light-Green", image: "#C5DB88" },
    { name: "Torquoise", image: "#6BF1D8" },
    { name: "Light-Blue", image: "#C5E3FF" },
    { name: "Light-Purple", image: "#D7BEF5" },
    { name: "Silver", image: "#C0C0C0" },
    { name: "Pink", image: "#FFC0CB" },
    { name: "Coral", image: "#FF7F50" },
    { name: "Orange", image: "#FFA500" },
    { name: "Green", image: "#008000" },
    { name: "Blue", image: "#0000FF" },
    { name: "Purple", image: "#800080" },
    { name: "Red", image: "#FF0000" },
    { name: "Camel", image: "#C19A6B" },
    { name: "Brown", image: "#A52A2A" },
    { name: "Khaki", image: "#F0E68C" },
    { name: "Navy", image: "#000080" },
    { name: "Wine", image: "#9E213F" },
    { name: "Gold", image: "#FFD700" },
  ];
  